name: samaj_parivaar_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_pay_upi: ^0.2.1
  firebase_core: ^4.2.1
  animations: ^2.1.0
  get: ^4.7.2
  http: ^1.5.0
  get_storage: ^2.1.1
  pinput: ^5.0.2
  image_picker: ^1.2.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
#  build_runner: ^2.10.1
#  freezed: ^3.2.3
#  json_serializable: ^6.11.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/add_post.png
    - assets/images/community.png
    - assets/images/community_people.png
    - assets/images/events.png
    - assets/images/google.png
    - assets/images/home.png
    - assets/images/logo.png
    - assets/images/person_profile.png
